-- ============================================================================
-- Local dev seed skeleton (ticket #3)
-- ============================================================================
-- Runs automatically after migrations on `supabase db reset` (see
-- [db.seed] in supabase/config.toml). Empty on purpose for now -- add real
-- seed data here once further tenant-scoped tables land; keep it idempotent
-- (safe to run repeatedly) and local-only (never seed anything resembling
-- production data or real credentials).
--
-- The real tenant schema (tenants, tenant_memberships, brands, locations)
-- landed in ticket #4: see
-- supabase/migrations/20260801040000_tenant_membership_brand_location_model.sql
-- -- follow that migration's tenant_id + RLS pattern for any new table.
--
-- Example of the shape a future seed might take, left commented out so this
-- file stays a no-op:
--
-- insert into tenants (id, name) values
--   ('11111111-1111-1111-1111-111111111111', 'Trattoria Da Mario'),
--   ('22222222-2222-2222-2222-222222222222', 'Burger Barn')
-- on conflict (id) do nothing;
